### ISSUE TITLE
Can you also add dropdownMatchSelectWidth from antd Select

### ISSUE THREAD

**Issue by tanDjent** [HelKyle/antd-multi-cascader#13]
It will fix one of the CSS issues of the dropdown
and if you can also add dropdownClassName later it will be great
but the dropdownMatchSelectWidth is the most important one

**Comment by HelKyle** [comment]
In the current UI design, I am afraid not. Maybe you can set the column width specifically.

```css
.antd-multi-cascader-column {
	width: 200px !important;
}
```
